[build]
  command = "npm install && npm run build"
  functions = "functions"

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/.netlify/functions/server/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "application/json"